INSERT INTO sections (handle,
                name, 
                description, 
                thumbnail, 
                content_url) 
VALUES ('introductions', 
        'Introductions', 
        'Learn basic Spanish greetings and introductions.', 
        'https://plus.unsplash.com/premium_photo-1664302336737-37fce6daca3c?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
        '/sections/introductions'),
        ('vital-signs', 
        'Vital Signs', 
        'Explore Spanish vocabulary related to taking vital signs.', 
        'https://plus.unsplash.com/premium_photo-1661431180276-943dc4b1ae98?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
        '/sections/vital-signs'),
        ('anatomy', 
        'Anatomy', 
        'Learn vocabulary related to general anatomy.', 
        'https://www.realityworks.com/wp-content/uploads/2019/08/HumanTorso-500wide.jpg', 
        '/sections/anatomy'),
        ('gait', 
        'Gait Training', 
        'Learn to instruct patients in safe gait patterns.', 
        'https://media.istockphoto.com/id/1194506777/photo/young-man-in-walking-rehabilitation-course-after-a-sport-injury.jpg?s=612x612&w=0&k=20&c=aHGE1IiPZxSdbZ8yxrpeyND6a3lfreU5RCLr5cx9EzA=', 
        '/sections/gait'),
        ('exercise', 
        'Exercise Instructions', 
        'Learn how to instruct patients to complete exercises.', 
        'https://plus.unsplash.com/premium_photo-1681996552732-29cfb91ac383?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
        '/sections/exercise'),
        ('balance', 
        'Balance', 
        'Learn how to instruct patients through balance exercises.', 
        'https://media.istockphoto.com/id/1501185766/photo/man-doing-physical-therapy-exercises-using-a-balance-ball.jpg?s=612x612&w=0&k=20&c=hHyQSYCGdCm48bEygS2S8B5M6pRPOH8E5oNYqAqGFaQ=', 
        '/sections/balance'),
        ('transfers', 
        'Transfer Training', 
        'Learn how to instruct patients in transfers and bed mobility.', 
        'https://www.physio.co.uk/images/difficulty-transferring/difficulty-transferring1.jpg', 
        '/sections/transfers'),
        ('dme', 
        'Medical Equipment', 
        'Learn vocabulary related to assistive devices and how to adjust them.', 
        'https://t3.ftcdn.net/jpg/05/26/53/92/360_F_526539234_MysOXDG96ZSnIIwbGcwBRAg2z9lzr161.jpg', 
        '/sections/dme'),
        ('modalities', 
        'Modalities', 
        'Learn vocabulary related to common physical therapy modalities.', 
        'https://media.istockphoto.com/id/1297947887/photo/female-physiotherapist-is-examining-to-her-patient.jpg?s=612x612&w=0&k=20&c=t49oAbBCRqeywIuYoyf9N9qQ3KYN2GL7Ct7l5P4Y1uc=', 
        '/sections/modalities');



INSERT INTO vocabulary (section_handle, 
                        english_word, 
                        spanish_word)
VALUES ('introductions', 'hello', 'hola'),
        ('introductions', 'goodbye', 'adiós'),
        ('introductions', 'How are you?', '¿Cómo está usted?'),
        ('introductions', 'My name is..', 'Me llamo ...'),
        ('introductions', 'I am a physical therapist assistant.', 'Soy un/a asistente de terapia física.'),
        ('vital-signs', 'blood pressure', 'presión arterial'),
        ('vital-signs', 'heart rate', 'frecuencia cardíaca'),
        ('vital-signs', 'temperature', 'temperatura'),
        ('vital-signs', 'How are you feeling today?', '¿Cómo te sientes hoy?'),
        ('vital-signs', 'Are you in pain?', '¿Estás sintiendo dolor?')
        ('anatomy', 'leg', 'pierna'),
        ('anatomy', 'arm', 'brazo'),
        ('anatomy', 'hip', 'cadera'),
        ('anatomy', 'knee', 'rodilla'),
        ('anatomy', 'ankle', 'tobillo'),
        ('gait', 'step', 'paso'),
        ('gait', 'walk', 'caminar'),
        ('gait', 'stride', 'zancada'),
        ('gait', 'take a bigger step', 'da un paso más grande'),
        ('gait', 'lift your foot', 'levanta el pie'),
        ('gait', 'lift your foot a little more', 'levanta un poco más el pie'),
        ('gait', 'step down', 'baja el pie'),
        ('gait', 'step down with your heel first', 'baja el pie con el talón primero'),
        ('gait', 'heel', 'talón'),
        ('gait', 'toe', 'dedo del pie'),
        ('gait', 'heel to toe', 'talón a dedo del pie'),
        ('balance', 'balance', 'equilibrio'),
        ('balance', 'stand', 'pararse'),
        ('balance', 'stand on one foot', 'pararse en un pie'),
        ('balance', 'step up', 'subir'),
        ('balance', 'walk', 'caminar'),
        ('balance', 'heel', 'talón'),
        ('balance', 'toe', 'dedo del pie'),
        ('balance', 'heel to toe', 'talón a dedo del pie'),
        ('balance', 'Walk taking sideways steps.', 'Caminar dando pasos de lado.'),
        ('balance', 'backwards', 'hacia atrás'),
        ('balance', 'Are you dizzy?', '¿Estás mareado?'),
        ('exercise', 'Bend your knee', 'Flexiona la rodilla'),
        ('exercise', 'Straighten your knee', 'Estira la rodilla'),
        ('exercise', 'Stand with upright posture', 'Ponte de pie con la postura recta'),
        ('exercise', 'Raise your arm', 'Levanta el brazo'),
        ('exercise', 'Lower your arm', 'Baja el brazo'),
        ('exercise', 'Reach for the sky', 'Alcanza hacia el cielo'),
        ('exercise', 'Rotate your torso to the left', 'Gira el torso hacia la izquierda'),
        ('exercise', 'Rotate your torso to the right', 'Gira el torso hacia la derecha'),
        ('exercise', 'Lift your leg', 'Levanta la pierna'),
        ('exercise', 'Squat down', 'Agáchate'),
        ('transfers', 'transfer', 'transferencia'),
        ('transfers', 'bed mobility', 'movilidad en la cama'),
        ('transfers', 'push up', 'empujar hacia arriba'),
        ('transfers', 'edge of the bed', 'borde de la cama'),
        ('transfers', 'sit down', 'siéntate'),
        ('transfers', 'reach', 'alcanzar'),
        ('transfers', 'scoot', 'deslizar'),
        ('transfers', 'roll to your side', 'rueda hacia tu lado'),
        ('transfers', 'side', 'lado'),
        ('transfers', 'sit up', 'sentarse'),
        ('transfers', 'lay down', 'acostarse'),
        ('transfers', 'stand up', 'ponerse de pie'),
        ('dme', 'medical equipment', 'equipo médico'),
        ('dme', 'wheelchair', 'silla de ruedas'),
        ('dme', 'walker', 'andador'),
        ('dme', 'crutches', 'muletas'),
        ('dme', 'cane', 'bastón'),
        ('dme', 'shower chair', 'silla de ducha'),
        ('dme', 'handrail', 'barandilla'),
        ('modalities', 'modality', 'modalidad'),
        ('modalities', 'physical therapy', 'terapia física'),
        ('modalities', 'electrical stimulation', 'estimulación eléctrica'),
        ('modalities', 'massage', 'masaje'),
        ('modalities', 'hot pack', 'compresa caliente'),
        ('modalities', 'traction', 'tracción'),
        ('modalities', 'ultrasound', 'ultrasonido'),
        ('modalities', 'therapeutic exercise', 'ejercicio terapéutico'),
        ('modalities', 'stretching', 'estiramiento'),
        ('modalities', 'strengthening', 'fortalecimiento'),
        ('modalities', 'balance training', 'entrenamiento de equilibrio'),
        ('modalities', 'manual therapy', 'terapia manual');
        
